// Countries for onboarding's Autocomplete field. Not exhaustive — the field
// also accepts free text for anything not listed.
export const COUNTRIES: string[] = [
  'Tunisia',
  'Algeria',
  'Morocco',
  'Libya',
  'Egypt',
  'Mauritania',
  'Sudan',
  'Saudi Arabia',
  'United Arab Emirates',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Jordan',
  'Lebanon',
  'Syria',
  'Iraq',
  'Palestine',
  'Yemen',
  'Turkey',
  'Iran',
  'Israel',
  'United States',
  'Canada',
  'Mexico',
  'Brazil',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'United Kingdom',
  'Ireland',
  'France',
  'Germany',
  'Spain',
  'Portugal',
  'Italy',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Iceland',
  'Poland',
  'Czech Republic',
  'Slovakia',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Greece',
  'Ukraine',
  'Russia',
  'Serbia',
  'Croatia',
  'Bosnia and Herzegovina',
  'Albania',
  'North Macedonia',
  'Slovenia',
  'Lithuania',
  'Latvia',
  'Estonia',
  'Malta',
  'Cyprus',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ghana',
  'Ethiopia',
  'Senegal',
  'Ivory Coast',
  'Cameroon',
  'Uganda',
  'Tanzania',
  'Somalia',
  'India',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'China',
  'Japan',
  'South Korea',
  'Indonesia',
  'Malaysia',
  'Singapore',
  'Philippines',
  'Thailand',
  'Vietnam',
  'Australia',
  'New Zealand',
  'Other',
];
