// Common native-language options for onboarding's Autocomplete field. Not
// exhaustive — the field also accepts free text for anything not listed.
export const LANGUAGES: string[] = [
  'Arabic',
  'Tunisian Arabic',
  'English',
  'French',
  'Spanish',
  'Portuguese',
  'Italian',
  'German',
  'Dutch',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Polish',
  'Russian',
  'Ukrainian',
  'Czech',
  'Slovak',
  'Romanian',
  'Hungarian',
  'Greek',
  'Turkish',
  'Hebrew',
  'Persian (Farsi)',
  'Urdu',
  'Hindi',
  'Bengali',
  'Punjabi',
  'Gujarati',
  'Marathi',
  'Tamil',
  'Telugu',
  'Kannada',
  'Malayalam',
  'Sinhala',
  'Nepali',
  'Chinese (Mandarin)',
  'Chinese (Cantonese)',
  'Japanese',
  'Korean',
  'Vietnamese',
  'Thai',
  'Khmer',
  'Lao',
  'Burmese',
  'Indonesian',
  'Malay',
  'Tagalog (Filipino)',
  'Swahili',
  'Amharic',
  'Somali',
  'Hausa',
  'Yoruba',
  'Igbo',
  'Zulu',
  'Xhosa',
  'Afrikaans',
  'Berber (Tamazight)',
  'Kurdish',
  'Pashto',
  'Armenian',
  'Georgian',
  'Azerbaijani',
  'Kazakh',
  'Uzbek',
  'Albanian',
  'Bosnian',
  'Serbian',
  'Croatian',
  'Bulgarian',
  'Macedonian',
  'Slovenian',
  'Lithuanian',
  'Latvian',
  'Estonian',
  'Icelandic',
  'Irish',
  'Welsh',
  'Maltese',
  'Haitian Creole',
];
